#include "http/EventJson.h"

#include "utils/DateTimeUtils.h"

#include <algorithm>
#include <cctype>

namespace voicecalendar::http
{
namespace
{
EventParseResult invalid(std::string message)
{
    EventParseResult result;
    result.errorMessage = std::move(message);
    return result;
}

std::string trim(std::string value)
{
    const auto isNotSpace = [](unsigned char character) {
        return std::isspace(character) == 0;
    };
    const auto first = std::find_if(value.begin(), value.end(), isNotSpace);
    const auto last = std::find_if(value.rbegin(), value.rend(), isNotSpace).base();
    if (first >= last)
    {
        return {};
    }
    return std::string(first, last);
}

} // namespace

Json::Value eventToJson(const models::Event& event)
{
    Json::Value json(Json::objectValue);
    json["id"] = event.id;
    json["title"] = event.title;
    json["description"] = event.description;
    json["date"] = event.date;
    json["startTime"] = event.startTime;
    if (event.endTime)
    {
        json["endTime"] = *event.endTime;
    }
    json["type"] = models::toStorageValue(event.type);
    if (event.categoryId)
    {
        json["categoryId"] = *event.categoryId;
    }
    json["reminderEnabled"] = event.reminderEnabled;
    json["createdAt"] = event.createdAt;
    json["updatedAt"] = event.updatedAt;
    return json;
}

EventParseResult parseEventInput(
    const Json::Value& json,
    const std::optional<std::string>& expectedId)
{
    if (json.isMember("id"))
    {
        if (!expectedId)
        {
            return invalid("id is generated by the server");
        }
        if (!json["id"].isString() || json["id"].asString() != *expectedId)
        {
            return invalid("id must match the request path");
        }
    }

    if (!json.isMember("title"))
    {
        return invalid("title is required");
    }
    if (!json["title"].isString())
    {
        return invalid("title must be a string");
    }
    auto title = trim(json["title"].asString());
    if (title.empty())
    {
        return invalid("title must not be empty");
    }

    if (!json.isMember("date"))
    {
        return invalid("date is required");
    }
    if (!json["date"].isString() || !utils::isValidDate(json["date"].asString()))
    {
        return invalid("date must be a valid YYYY-MM-DD value");
    }

    if (!json.isMember("startTime"))
    {
        return invalid("startTime is required");
    }
    if (!json["startTime"].isString() ||
        !utils::parseTimeToMinutes(json["startTime"].asString()))
    {
        return invalid("startTime must be a valid HH:mm value");
    }

    models::Event event;
    event.title = std::move(title);
    event.date = json["date"].asString();
    event.startTime = json["startTime"].asString();

    if (json.isMember("description"))
    {
        if (!json["description"].isString())
        {
            return invalid("description must be a string");
        }
        event.description = json["description"].asString();
    }

    if (json.isMember("endTime") && !json["endTime"].isNull())
    {
        if (!json["endTime"].isString() ||
            !utils::parseTimeToMinutes(json["endTime"].asString()))
        {
            return invalid("endTime must be null or a valid HH:mm value");
        }
        event.endTime = json["endTime"].asString();
    }

    if (json.isMember("type"))
    {
        if (!json["type"].isString())
        {
            return invalid("type must be a string");
        }
        const auto eventType = models::eventTypeFromStorageValue(json["type"].asString());
        if (!eventType)
        {
            return invalid("type must be schedule, course, work, or reminder");
        }
        event.type = *eventType;
    }

    if (json.isMember("categoryId") && !json["categoryId"].isNull())
    {
        if (!json["categoryId"].isString() || trim(json["categoryId"].asString()).empty())
        {
            return invalid("categoryId must be null or a non-empty string");
        }
        event.categoryId = json["categoryId"].asString();
    }

    if (json.isMember("reminderEnabled"))
    {
        if (!json["reminderEnabled"].isBool())
        {
            return invalid("reminderEnabled must be a boolean");
        }
        event.reminderEnabled = json["reminderEnabled"].asBool();
    }

    if (expectedId)
    {
        event.id = *expectedId;
    }

    EventParseResult result;
    result.event = std::move(event);
    result.valid = true;
    return result;
}

} // namespace voicecalendar::http
